Repository eclipse-zenoh/zenoh-java, pull requests merged in 2024-12, with the labels that each got.

#159 fix: exclude internal from automatic changelog
  .github/release.yml
Labels: internal

#162 Native loading refactor
  zenoh-java/src/jvmMain/kotlin/io/zenoh/Target.kt
  zenoh-java/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
Labels: release, internal

#163 Aarch64 windows support
  .github/workflows/publish-jvm.yml
  zenoh-java/src/jvmMain/kotlin/io/zenoh/Target.kt
  zenoh-java/src/jvmMain/kotlin/io/zenoh/Zenoh.kt
Labels: enhancement, release

#164 Publications alignment
  .github/workflows/ci.yml
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
  .github/workflows/release.yml
  examples/build.gradle.kts
  zenoh-java/build.gradle.kts
Labels: release, internal
