Repository eclipse-zenoh/zenoh-java, pull requests merged in 2024-09, with the labels that each got.

#144 Readme update after 1.0.0-beta.1 release.
  README.md
Labels: documentation

#150 fix: remove deprecated imports & lock file update
  zenoh-jni/Cargo.lock
  zenoh-jni/src/publisher.rs
  zenoh-jni/src/query.rs
  zenoh-jni/src/session.rs
Labels: release, internal

#154 chore: update release.yml for required labels
  .github/release.yml
Labels: internal
