Repository eclipse-zenoh/zenoh-java, pull requests merged in 2025-01, with the labels that each got.

#167 Fix ZGet example
  examples/src/main/java/io/zenoh/ZGet.java
Labels: bug, release, internal

#169 Refactor examples
  examples/src/main/java/io/zenoh/ZInfo.java
  examples/src/main/java/io/zenoh/ZLiveliness.java
  examples/src/main/java/io/zenoh/ZPing.java
  examples/src/main/java/io/zenoh/ZPong.java
  examples/src/main/java/io/zenoh/ZPub.java
  examples/src/main/java/io/zenoh/ZPut.java
  examples/src/main/java/io/zenoh/ZSubThr.java
Labels: internal

#170 Javadoc flavored documentation
  .github/workflows/publish-dokka.yml
  build.gradle.kts
Labels: documentation, release, internal

#171 Disabling java tests when Android is enabled
  zenoh-java/build.gradle.kts
Labels: bug, internal

#173 String overloads as an alternative to ZBytes
  examples/src/main/java/io/zenoh/ZLiveliness.java
  examples/src/main/java/io/zenoh/ZPub.java
  examples/src/main/java/io/zenoh/ZPut.java
  examples/src/main/java/io/zenoh/ZQuerier.java
  examples/src/main/java/io/zenoh/ZQueryable.java
  zenoh-java/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/ext/ZDeserializer.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/pubsub/DeleteOptions.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/pubsub/Publisher.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/pubsub/PutOptions.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/query/Get.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/query/Querier.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/query/Query.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/query/Queryable.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/query/Reply.kt
  zenoh-java/src/jvmTest/java/io/zenoh/EncodingTest.java
Labels: enhancement, release

#174 fix: update relative cargo.toml path
  examples/build.gradle.kts
  zenoh-java/build.gradle.kts
Labels: bug, internal

#175 Upgrade rust android gradle plugin to 0.9.6
  build.gradle.kts
Labels: release, internal

#179 Examples fat JARs
  build.gradle.kts
  examples/README.md
  examples/build.gradle.kts
Labels: enhancement, internal

#182 Maven publications
  .github/workflows/ci.yml
  .github/workflows/publish-android.yml
  .github/workflows/publish-dokka.yml
  .github/workflows/publish-jvm.yml
  .github/workflows/release.yml
  build.gradle.kts
  examples/build.gradle.kts
  gradle.properties
  zenoh-java/build.gradle.kts
Labels: release, internal

#183 Readme update
  .github/workflows/ci.yml
  README.md
  doc_icon.png
Labels: documentation, release, internal

#185 fix: set default for maven_publish
  .github/workflows/ci.yml
  .github/workflows/publish-android.yml
  .github/workflows/publish-jvm.yml
  .github/workflows/release.yml
Labels: internal
