Repository eclipse-zenoh/zenoh-java, pull requests merged in 2025-03, with the labels that each got.

#211 Bump Rust toolchain to 1.85
  rust-toolchain.toml
  zenoh-jni/src/key_expr.rs
  zenoh-jni/src/session.rs
Labels: dependencies

#225 fix: add rust 1.75 CI check
  .github/workflows/ci.yml
Labels: internal

#230 Fix potential crash after failed Zenoh.open()
  zenoh-java/src/commonMain/kotlin/io/zenoh/Session.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/jni/JNILiveliness.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/jni/JNISession.kt
  zenoh-jni/src/session.rs
Labels: bug, release
