Repository eclipse-zenoh/zenoh-java, pull requests merged in 2025-04, with the labels that each got.

#199 Adopt the different congestion control defaults as in Rust
  zenoh-java/src/commonMain/kotlin/io/zenoh/pubsub/DeleteOptions.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/pubsub/PublisherOptions.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/pubsub/PutOptions.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/qos/QoS.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/query/Get.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/query/Querier.kt
  zenoh-java/src/commonMain/kotlin/io/zenoh/query/Reply.kt
  zenoh-java/src/jvmTest/java/io/zenoh/QuerierTest.java
  zenoh-java/src/jvmTest/java/io/zenoh/QueryableTest.java
Labels: enhancement, release

#243 Fix flaky query tests
  zenoh-java/src/jvmTest/java/io/zenoh/GetTest.java
  zenoh-java/src/jvmTest/java/io/zenoh/QuerierTest.java
  zenoh-java/src/jvmTest/java/io/zenoh/QueryableTest.java
  zenoh-java/src/jvmTest/java/io/zenoh/UserAttachmentTest.java
Labels: bug, internal

#254 Session: save querier and publisher as weak refs
  zenoh-java/src/commonMain/kotlin/io/zenoh/Session.kt
Labels: bug, internal

#252 chore: update ubuntu runners to ubuntu-24.04
  .github/workflows/publish-jvm.yml
Labels: internal
